### ISSUE TITLE
[Bug]: Rubocop does not respect its config when run during precommit hook

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1971]
## Description

When making a change to the schema, on commit it was flagged for all sorts of changes. 

In the rubocop config (`.rubocop.yml`):

```
AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"
    - "db/schema.rb"
```  

On commiting a schema change:

![Screenshot 2023-07-20 at 09 49 31](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/aec058b1-0a8b-492e-9708-71d335708c28)

## Solution

Possible solution here:

https://stackoverflow.com/questions/63614897/rubocop-exclude-files-from-a-list-given-on-command-line

change to possibly make in package.json

```
   "lint-staged": {
        "*.{css,html,js,json,md,scss,yml}": "prettier --write",
        "{*.{rb,jbuilder,rake,ru},.simplecov,Gemfile,Rakefile}": "bundle exec rubocop --force-exclusion --autocorrect"
    },
    
```
